"""Public bs-pack, teacher-bank, and paired-evaluation APIs."""

from pathlib import Path
from collections.abc import Sequence
from typing import Any

from .contract import (
    MANIFEST_NAME,
    PackValidationError,
    export_pack,
    load_manifest,
    verify_pack,
)
from .resident_repair_api import (
    BackpackArtifact,
    PipelineResult,
    ResidentRepairAPI,
    UniformBuild,
    V7_UNIFORM_TIERS,
)
from .banana_v1_runtime_adapter import (
    BananaV1All43Adapter,
    BananaV1MemberBinding,
)
from .hf_moe import (
    HF_AUXILIARY_LAYER_RULE,
    HF_CLIENT_BOOKKEEPING_PREFIXES,
    HF_ROUTED_SCOPE_SCHEMA,
    HF_SOLVE_EXTRA_REQUIREMENT,
    HF_SOURCE_ADMISSION_SCHEMA,
    HF_UNIFORM_ARTIFACT_SCHEMA,
    HF_UNIFORM_PLAN_SCHEMA,
    admit_hf_source,
    build_hf_moe_uniform,
    build_hf_moe_uniform_shard,
    discover_hf_moe_routed_scope,
    estimate_hf_moe_uniform,
    open_hf_moe_uniform,
    open_hf_moe_uniform_shard,
    plan_hf_moe_uniform,
    preflight_hf_moe_output_fit,
    union_hf_moe_uniform_shards,
)
from .hf_balanced64 import (
    BALANCED64_HARDWARE_CONTRACT_SCHEMA,
    Balanced64CapabilityError,
    Balanced64Runtime,
    Balanced64Tokenizer,
    balanced64_hardware_contract,
    build_balanced64_token_ledger,
    capture_balanced64_teacher,
    preflight_balanced64_runtime,
    recover_balanced64_source_text,
    score_balanced64_pre,
)
from .production_rails import ProductionRails, ProductionRailsError
from .anchor import (
    AnchorEvaluationError,
    aggregate_scores,
    build_bank_manifest,
    compare_training_rails,
    create_balanced_subset,
    emit_solver_row,
    import_producer,
    materialize_candidate_producer,
    materialize_bank,
    register_bank,
    resolve_bank_identities,
    status_report,
    validate_bank_manifest,
)
from .bank import build_bank, verify_bank
from .bpw import (
    BPW_ACCOUNTING_SCHEMA,
    BpwAccountingError,
    build_bpw_accounting,
    require_comparable_bpw,
    verify_bpw_accounting,
)
from .backpack import (
    BackpackPlan,
    anchor_backpack,
    anchor_backpack_candidates,
    candidate_artifact_root,
    export_backpack_lifecycle,
    generate_backpack_candidates,
    generate_qtip_backpack_candidate,
    generate_vector_vq_backpack_candidate,
    inspect_backpack,
    materialize_backpack_source,
    predict_backpack,
    reuse_backpack_receipts,
    solve_backpack,
    status_backpack,
)
from .backpack_providers import (
    BQ23_PROVIDER_IDS,
    BackpackFamilyActivation,
    BackpackFamilyProvider,
    BackpackWireArtifact,
    BackpackWirePrice,
    backpack_provider_from_declaration,
    bq23_backpack_family_providers,
    bind_native_mxfp4_backpack_candidate,
    builtin_backpack_family_providers,
    fixed_d4_backpack_provider,
    generate_backpack_candidate,
    materialize_backpack_assignment,
    native_mxfp4_backpack_provider,
    price_backpack_candidate,
    predict_backpack_candidate,
    qtip_ring_backpack_provider,
    resolve_backpack_family_provider,
    vector_vq_backpack_provider,
    verify_backpack_candidate,
)
from .backpack_contextual import (
    ContextualValuationError,
    build_contextual_delta_ledger,
    run_contextual_trust_solve,
    run_contextual_value_update,
    solve_contextual_trust_region,
)
from .backpack_contextual_candidate import materialize_contextual_change
from .backpack_contextual_measure import record_contextual_swap_measurement
from .backpack_contextual_prepare import prepare_contextual_iteration
from .backpack_exact64 import EXACT64_TERMINAL_SCHEMA, bind_backpack_exact64
from .backpack_dimensions import (
    bind_mixed_v7_physical_dimensions as bind_mixed_v7_physical_dimensions,
    preflight_mixed_backpack_config as preflight_mixed_backpack_config,
    preflight_mixed_v7_recovery_plan as preflight_mixed_v7_recovery_plan,
    solve_mixed_backpack_config as solve_mixed_backpack_config,
)
from .mixed_transaction import (
    prepare_mixed_backpack_transaction,
    stage_mixed_v7_member_index,
)

from .backpack_selection import select_measured_nonworse
from .measured_backpack_spsa import (
    build_hierarchical_groups,
    command_evaluator,
    load_full_wire_menu,
    load_routing_usage,
    measured_objective,
    project_group_logits,
    refine_influential_groups,
    run_measured_spsa,
)
from .backpack_virtual import (
    materialize_provenance_virtual_backpack,
    materialize_virtual_backpack,
    verify_virtual_backpack,
)
from .locality import require_local_backpack_inputs, require_local_path
from .staging import stage_qsfp_manifest
from .evaluate import evaluate_paired, verify_evaluation
from .exl3_loader import admit_exl3_storage_alias, resolve_exl3_storage_prefix
from .fixed_d4 import (
    materialize_fixed_d4,
    persist_fixed_d4_solve,
    prepare_fixed_d4_solve_config,
    produce_fixed_d4_layerwise_logits,
    produce_fixed_d4_logits,
    solve_fixed_d4_exact,
    verify_fixed_d4_model,
)
from .persistent import UpdateQueue
from .provenance_wire import (
    build_full_wire_provenance_ledger,
    run_full_wire_provenance_solve,
)
from .qtip1 import (
    EncodedQtip,
    QTIP1_GEOMETRY,
    QTIP2_GEOMETRY,
    QtipGeometry,
    QtipProviderComponent,
    QtipProviderDeclaration,
    QtipWireConsumer,
    assign_qtip_provider_components,
    decode_qtip,
    encode_qtip,
    gaussian_tlut,
    pack_qtip_states,
    qtip1_5_provider_declaration,
    qtip1_provider_declaration,
    qtip_provider_counts,
    unpack_qtip_states,
    verify_qtip_wire,
    write_encoded_qtip_wire,
    write_qtip_wire,
)
from .qtip_v7_batch import materialize_qtip2_v7_sources, produce_qtip2_v7_batch10
from .qtip_v7_joint_workflow import (
    aggregate_balanced64,
    compare_aggregates,
    inspect_joint_inputs,
    launch_balanced64_shards,
    materialize_joint,
    verify_joint_checkpoint,
)
from .update_service import serve_persistent_updates


def solve_qtip_profiles(
    config_root: str | Path,
    root: str | Path,
    layer: int,
    *,
    batch_size: int = 1,
    config_paths: Sequence[str | Path] | None = None,
    limit: int | None = None,
    tier: str | None = None,
    all_cells: bool = False,
    profile_mode: bool = False,
    resume: bool = True,
    resume_flag_explicit: bool = False,
    kernel_cache_root: str | Path | None = None,
) -> dict[str, Any]:
    """Solve a discoverable QTIP config set through one resident process.

    ``batch_size > 1`` selects the exact K2/full16 cross-unit build path and
    fails closed rather than falling back to serial unit solves.
    """
    from .solver_qtip_profile import main_many

    return main_many(
        Path(config_root),
        Path(root),
        int(layer),
        batch_size=batch_size,
        config_paths=(
            [Path(path) for path in config_paths] if config_paths is not None else None
        ),
        limit=limit,
        tier=tier,
        all_cells=all_cells,
        profile_mode=profile_mode,
        resume=resume,
        resume_flag_explicit=resume_flag_explicit,
        kernel_cache_root=(
            Path(kernel_cache_root) if kernel_cache_root is not None else None
        ),
    )


__all__ = [
    "MANIFEST_NAME",
    "BananaV1All43Adapter",
    "BananaV1MemberBinding",
    "BQ23_PROVIDER_IDS",
    "BPW_ACCOUNTING_SCHEMA",
    "BpwAccountingError",
    "PackValidationError",
    "AnchorEvaluationError",
    "BackpackFamilyActivation",
    "BackpackFamilyProvider",
    "BackpackArtifact",
    "BackpackPlan",
    "BackpackWireArtifact",
    "BackpackWirePrice",
    "ContextualValuationError",
    "EXACT64_TERMINAL_SCHEMA",
    "EncodedQtip",
    "PipelineResult",
    "ProductionRails",
    "ProductionRailsError",
    "QTIP1_GEOMETRY",
    "QTIP2_GEOMETRY",
    "QtipGeometry",
    "QtipProviderComponent",
    "QtipProviderDeclaration",
    "QtipWireConsumer",
    "ResidentRepairAPI",
    "UniformBuild",
    "V7_UNIFORM_TIERS",
    "HF_SOURCE_ADMISSION_SCHEMA",
    "HF_UNIFORM_ARTIFACT_SCHEMA",
    "HF_UNIFORM_PLAN_SCHEMA",
    "admit_hf_source",
    "build_hf_moe_uniform",
    "build_hf_moe_uniform_shard",
    "estimate_hf_moe_uniform",
    "open_hf_moe_uniform",
    "open_hf_moe_uniform_shard",
    "plan_hf_moe_uniform",
    "preflight_hf_moe_output_fit",
    "union_hf_moe_uniform_shards",
    "Balanced64Runtime",
    "Balanced64Tokenizer",
    "build_balanced64_token_ledger",
    "capture_balanced64_teacher",
    "preflight_balanced64_runtime",
    "recover_balanced64_source_text",
    "score_balanced64_pre",
    "UpdateQueue",
    "aggregate_scores",
    "aggregate_balanced64",
    "admit_exl3_storage_alias",
    "anchor_backpack",
    "anchor_backpack_candidates",
    "assign_qtip_provider_components",
    "backpack_provider_from_declaration",
    "bq23_backpack_family_providers",
    "bind_native_mxfp4_backpack_candidate",
    "bind_backpack_exact64",
    "bind_mixed_v7_physical_dimensions",
    "build_bank",
    "build_bank_manifest",
    "build_bpw_accounting",
    "build_contextual_delta_ledger",
    "build_full_wire_provenance_ledger",
    "build_hierarchical_groups",
    "builtin_backpack_family_providers",
    "candidate_artifact_root",
    "compare_training_rails",
    "command_evaluator",
    "compare_aggregates",
    "create_balanced_subset",
    "decode_qtip",
    "emit_solver_row",
    "encode_qtip",
    "evaluate_paired",
    "export_backpack_lifecycle",
    "export_pack",
    "fixed_d4_backpack_provider",
    "generate_backpack_candidate",
    "generate_backpack_candidates",
    "generate_qtip_backpack_candidate",
    "generate_vector_vq_backpack_candidate",
    "gaussian_tlut",
    "import_producer",
    "inspect_joint_inputs",
    "inspect_backpack",
    "launch_balanced64_shards",
    "load_manifest",
    "load_full_wire_menu",
    "load_routing_usage",
    "materialize_backpack_assignment",
    "materialize_backpack_source",
    "materialize_contextual_change",
    "materialize_provenance_virtual_backpack",
    "materialize_virtual_backpack",
    "measured_objective",
    "materialize_bank",
    "materialize_candidate_producer",
    "materialize_fixed_d4",
    "materialize_qtip2_v7_sources",
    "materialize_joint",
    "native_mxfp4_backpack_provider",
    "pack_qtip_states",
    "persist_fixed_d4_solve",
    "preflight_mixed_backpack_config",
    "prepare_mixed_backpack_transaction",
    "stage_mixed_v7_member_index",
    "prepare_fixed_d4_solve_config",
    "price_backpack_candidate",
    "predict_backpack",
    "predict_backpack_candidate",
    "prepare_contextual_iteration",
    "project_group_logits",
    "produce_fixed_d4_layerwise_logits",
    "produce_fixed_d4_logits",
    "produce_qtip2_v7_batch10",
    "qtip1_5_provider_declaration",
    "qtip1_provider_declaration",
    "qtip_provider_counts",
    "qtip_ring_backpack_provider",
    "register_bank",
    "refine_influential_groups",
    "require_comparable_bpw",
    "record_contextual_swap_measurement",
    "resolve_bank_identities",
    "resolve_exl3_storage_prefix",
    "resolve_backpack_family_provider",
    "reuse_backpack_receipts",
    "require_local_backpack_inputs",
    "require_local_path",
    "run_contextual_trust_solve",
    "run_contextual_value_update",
    "run_full_wire_provenance_solve",
    "run_measured_spsa",
    "serve_persistent_updates",
    "solve_backpack",
    "solve_mixed_backpack_config",
    "solve_contextual_trust_region",
    "solve_fixed_d4_exact",
    "solve_qtip_profiles",
    "status_backpack",
    "status_report",
    "stage_qsfp_manifest",
    "select_measured_nonworse",
    "unpack_qtip_states",
    "validate_bank_manifest",
    "vector_vq_backpack_provider",
    "verify_bank",
    "verify_bpw_accounting",
    "verify_evaluation",
    "verify_backpack_candidate",
    "verify_virtual_backpack",
    "verify_fixed_d4_model",
    "verify_joint_checkpoint",
    "verify_pack",
    "verify_qtip_wire",
    "write_encoded_qtip_wire",
    "write_qtip_wire",
]
